["BLB"]
["TLL"]
["BRR"]
["TRT"]
["BRB"]
["BLL"]
["TRR"]
["TLT"]
["TLL", "TRR"]
["BRB", "TRT"]
["BLB", "TLT"]
["BLL", "BRR"]
["TLT", "TRT"]
["BRR", "TRR"]
["BLL", "TLL"]
["BLB", "BRB"]
["BRB", "BRR"]
["BLB", "BLL"]
["TRR", "TRT"]
["TLL", "TLT"]
["BLB", "TRR"]
["BRB", "TLL"]
["BRR", "TLT"]
["BLL", "TRT"]
["BLB", "TLL"]
["TLL", "TRT"]
["BLB", "BRR"]
["BRR", "TRT"]
["BLB", "BRB", "BRR"]
["BLB", "BLL", "TLL"]
["BRR", "TRR", "TRT"]
["TLL", "TLT", "TRT"]
["BLB", "BLL", "BRB"]
["BLL", "TLL", "TLT"]
["BRB", "BRR", "TRR"]
["TLT", "TRR", "TRT"]
["BLB", "BLL", "TRR", "TRT"]
["BRB", "BRR", "TLL", "TLT"]
["BLB", "BLL", "BRB", "BRR"]
["BLB", "BLL", "TLL", "TLT"]
["BRB", "BRR", "TRR", "TRT"]
["TLL", "TLT", "TRR", "TRT"]
["BLB", "BRB", "TLT", "TRT"]
["BLL", "BRR", "TLL", "TRR"]
["BLB", "BLL", "BRB", "TLL"]
["BLL", "TLL", "TLT", "TRT"]
["BLB", "BRB", "BRR", "TRR"]
["BRR", "TLT", "TRR", "TRT"]
["BLB", "BLL", "TLL", "TRR"]
["BRB", "TLL", "TLT", "TRT"]
["BLB", "BRB", "BRR", "TLT"]
["BLL", "BRR", "TRR", "TRT"]
["BRB", "BRR", "TLL", "TRR"]
["BLB", "BLL", "BRB", "TRT"]
["BLB", "TLT", "TRR", "TRT"]
["BLL", "BRR", "TLL", "TLT"]
["BLB", "BLL", "BRB", "BRR", "TLL", "TRR"]
["BLB", "BLL", "BRB", "TLL", "TLT", "TRT"]
["BLB", "BRB", "BRR", "TLT", "TRR", "TRT"]
["BLL", "BRR", "TLL", "TLT", "TRR", "TRT"]
["BRB", "BRR", "TLL", "TLT", "TRR", "TRT"]
["BLB", "BLL", "BRB", "BRR", "TRR", "TRT"]
["BLB", "BLL", "TLL", "TLT", "TRR", "TRT"]
["BLB", "BLL", "BRB", "BRR", "TLL", "TLT"]
["BLB", "BLL", "BRB", "BRR", "TLL", "TLT", "TRR", "TRT"]





